name: setup:di:compile
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - PHP_VERSION: php74-fpm
            MAGENTO_VERSION: 2.3.7-p3
          - PHP_VERSION: php82-fpm
            MAGENTO_VERSION: 2.4.6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Docker
        run: docker run --detach --name magento-project-community-edition michielgerritsen/magento-project-community-edition:${{ matrix.PHP_VERSION }}-magento${{ matrix.MAGENTO_VERSION }}

      - name: Upload the code into the docker container
        run: docker cp $(pwd)/. magento-project-community-edition:/data/extensions/mollie-magento2-analytics/

      - name: Install Mollie and Mollie Analytics extensions
        run: docker exec magento-project-community-edition ./install-composer-package mollie/magento2 mollie/magento2-analytics:"@dev"

      - name: Run setup:di:compile
        run: docker exec magento-project-community-edition ./retry "php bin/magento setup:di:compile"
